version: '3.0'
services:
  postgres:
    build: db/
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    image: thepyonic/home_lib_db
    volumes:
      - db_logs:/logs:z
      - db_data:/var/lib/postgresql/data
    networks:
      - home_lib_netw

  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    image: thepyonic/home_lib_api
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - home_lib_netw
    depends_on:
      - postgres

volumes:
  db_data:
  app_logs:
  db_logs:

networks:
  home_lib_netw:
    driver: bridge
